name: box64-with-gl4es
version: "latest"
summary: Linux Userspace x86_64 Emulator with a twist
description: |
  Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64-bit little-endian).

  You can find many Box64 videos on the MicroLinux, Pi Labs or The Byteman YouTube channels.

  Since Box64 uses the native versions of some "system" libraries, like libc, libm, SDL, and OpenGL, it's easy to integrate and use with most applications, and performance can be surprisingly high in many cases.

  Box64 integrates with DynaRec (dynamic recompiler) for the ARM64 platform, providing a speed boost between 5 to 10 times faster than using only the interpreter.

  # Instructions:

  Enable the system-wide interpreter by following the steps in the following command:

  `box64-with-gl4es.setup`

  # Enabling GL4ES:

  To make use of GL4ES on GLES-only hardware, export the environment variable `GL4ES=1`. To use GL4ES on non-GBM systems like libhybris, export the environment variable `GL4ES_GBM=0`.

  And done!

grade: stable
confinement: strict
base: core22
architectures:
  - arm64
compression: lzo

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/X11/locale
  /usr/share/zenity:
    symlink: $SNAP/usr/share/zenity

apps:
  box64:
    command: bin/graphics-core22-wrapper $SNAP/bin/runner
    extensions: [ gnome ]
    plugs: [ home, removable-media, audio-record, audio-playback, alsa, wayland, x11, desktop, desktop-legacy, gsettings, opengl, mount-observe, calendar-service, browser-support, hardware-observe, fuse-support ]
  wine64:
    command: bin/graphics-core22-wrapper $SNAP/bin/wine64runner
    extensions: [ gnome ]
    plugs: [ home, removable-media, audio-record, audio-playback, alsa, wayland, x11, desktop, desktop-legacy, gsettings, opengl, mount-observe, calendar-service, browser-support, hardware-observe, fuse-support ]
  setup:
    command: bin/setup

lint:
  ignore:
    - library

parts:
  gl4es-gbm:
    source: https://github.com/fredldotme/gl4es.git
    source-branch: box64andwine
    source-type: git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/gl4es-gbm
      - -DMULTIARCH_PREFIX=$CRAFT_ARCH_TRIPLET
      - -DNO_CONF_INSTALL=1
      - -DGLVND=OFF
      - -DNOX11=OFF
      - -DNOEGL=OFF
      - -DEGL_WRAPPER=OFF
      - -DNO_GBM=OFF
    build-packages:
      - cmake
      - libx11-dev
  gl4es-nogbm:
    source: https://github.com/fredldotme/gl4es.git
    source-branch: box64andwine
    source-type: git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/gl4es-nogbm
      - -DMULTIARCH_PREFIX=$CRAFT_ARCH_TRIPLET
      - -DNO_CONF_INSTALL=1
      - -DGLVND=OFF
      - -DNOX11=OFF
      - -DNOEGL=OFF
      - -DEGL_WRAPPER=OFF
      - -DNO_GBM=ON
    build-packages:
      - cmake
      - libx11-dev
  box64-4k:
    source: https://github.com/ptitSeb/box64.git
    source-type: git
    source-branch: main
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/4k
      - -DNO_CONF_INSTALL=1
    build-packages:
      - cmake
      - python3
    override-prime: |
      craftctl default
      cp $CRAFT_PART_SRC_WORK/system/box64.box64rc $CRAFT_PRIME/
  box64-16k:
    source: https://github.com/ptitSeb/box64.git
    source-type: git
    source-branch: main
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/16k
      - -DM1=1
      - -DNO_CONF_INSTALL=1
      - -DNO_LIB_INSTALL=1
    build-packages:
      - cmake
      - python3
  runner:
    after: [ box64-4k, box64-16k, gl4es-gbm, gl4es-nogbm ]
    source: snap/local
    plugin: dump
    stage-packages:
      - util-linux
      - zenity
      - libsdl1.2-compat
      - libsdl1.2-compat-shim
      - libsdl1.2debian
      - libsdl2-2.0-0
      - libvorbisfile3
      - libalure1
      - libalut0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libayatana-appindicator3-1
      - libbz2-1.0
      - libcairo2
      - libcap2
      - libcrypt1
      - libcurl4
      - libcairo2
      - libdbus-glib-1-2
      - libdbusmenu-glib4
      - libevent-2.1-7
      - libexpat1
      - libfaudio0
      - libfl2
      - libgconf-2-4
      - libpixman-1-0
      - libjack0
      - libportaudio2
      - libasound2
      - libbsd0
      - libfuse2
      - libfuse3-3
      - libharfbuzz0b
      - libnuma1
      - libogg0
      - libre0
      - libsndfile1
      - libtinfo6
      - libusb-1.0-0
      - libuuid1
      - libvorbis0a
      - libz3-4
      - liblzma5
      - libmpg123-0
      - libnotify4
      - libnsl2
      - libnspr4
      - libnss3
      - libopenal1
      - libpam0g
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpng16-16
      - libsdl2-2.0-0
      - libsdl2-gfx-1.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libsdl2-ttf-2.0-0
      - libsdl-image1.2
      - libsdl-mixer1.2
      - libsdl-net1.2
      - libsdl-ttf2.0-0
      - libselinux1
      - libsmpeg0
      - libunwind8
      - libxml2
      - libxslt1.1
      - libxkbcommon-x11-0
      - wine
      - wine64
    override-prime: |
      craftctl default
      ln -sf wine-stable $CRAFT_PRIME/usr/bin/wine
      ln -sf wine64-stable $CRAFT_PRIME/usr/bin/wine64
      ln -sf winecfg $CRAFT_PRIME/usr/bin/winecfg
      sed -i "s/\/usr\/lib\/wine/\$SNAP\/usr\/lib\/wine/g" $CRAFT_PRIME/usr/lib/wine/wineserver
  graphics-core22:
    after: [ runner ]
    source: https://github.com/MirServer/graphics-core.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
